from setuptools import setup, find_packages

setup(
    name="system_tool",
    version="0.1.0",
    description="Toolbox for data analysis and ML",
    author="User",
    package_dir={"": "./project"},
    packages=['project', 'project.toolBox', 'project.toolBox.system_tool',
              'project.toolBox.system_tool.cleaning_preprocessing',
              'project.toolBox.system_tool.cleaning_preprocessing.completeness',
              'project.toolBox.system_tool.cleaning_preprocessing.consistency',
              'project.toolBox.system_tool.cleaning_preprocessing.purity',
              'project.toolBox.system_tool.eda_visualization',
              'project.toolBox.system_tool.eda_visualization.distribution_insight',
              'project.toolBox.system_tool.eda_visualization.relationship_insight',
              'project.toolBox.system_tool.eda_visualization.reliability_insight',
              'project.toolBox.system_tool.feature_engineering',
              'project.toolBox.system_tool.feature_engineering.categorical_transform',
              'project.toolBox.system_tool.feature_engineering.feature_selection',
              'project.toolBox.system_tool.feature_engineering.numeric_transform',
              'project.toolBox.system_tool.ml_modeling',
              'project.toolBox.system_tool.ml_modeling.supervised_learning',
              'project.toolBox.system_tool.ml_modeling.unsupervised_learning',
              'project.toolBox.system_tool.model_evaluation',
              'project.toolBox.system_tool.model_evaluation.classification_eval',
              'project.toolBox.system_tool.model_evaluation.regression_eval',
              'project.toolBox.system_tool.overview_diagnosis',
              'project.toolBox.system_tool.overview_diagnosis.basic_archive',
              'project.toolBox.system_tool.overview_diagnosis.quality_diagnosis'],
    python_requires='>=3.8',
    install_requires=[
        "pandas>=2.0.0",
        "numpy>=1.24.0",
        "matplotlib>=3.7.0",
        "scikit-learn>=1.3.0",
    ],
)